export type {
  ActionIR,
  AdminPageIR,
  AjaxHandlerIR,
  CustomPostTypeIR,
  CustomTaxonomyIR,
  FilterIR,
  FunctionBodyIR,
  HookContext,
  ParameterIR,
  PluginIR,
  PluginMetadata,
  RawActionDecorator,
  RawAdminPageDecorator,
  RawAjaxHandlerDecorator,
  RawCustomPostTypeDecorator,
  RawCustomTaxonomyDecorator,
  RawFilterDecorator,
  RawLifecycleDecorator,
  RawPluginData,
  RawPluginDecorator,
  RawRestRouteDecorator,
  RawSettingDecorator,
  RawShortcodeDecorator,
  RestRouteIR,
  SettingIR,
  ShortcodeIR,
} from './plugin-ir.js';
