export type {
  PluginIR,
  PluginMetadata,
  ActionIR,
  FilterIR,
  SettingIR,
  AdminPageIR,
  ShortcodeIR,
  FunctionBodyIR,
  ParameterIR,
  HookContext,
  RawPluginData,
  RawPluginDecorator,
  RawActionDecorator,
  RawFilterDecorator,
  RawSettingDecorator,
  RawAdminPageDecorator,
  RawShortcodeDecorator,
  RawLifecycleDecorator,
  CustomPostTypeIR,
  CustomTaxonomyIR,
  RestRouteIR,
  AjaxHandlerIR,
  RawCustomPostTypeDecorator,
  RawCustomTaxonomyDecorator,
  RawRestRouteDecorator,
  RawAjaxHandlerDecorator,
} from './plugin-ir.js';
