/**
 * Diagnostics Routes — Admin Error Viewing
 *
 * Last-error endpoint is auto-generated by @DiagnosticsRoute().
 */

import { DiagnosticsRoute } from '@amitgurbani/wpts';

@DiagnosticsRoute()
class ClarityDiagnostics {}
