export interface PluginConfig {
  slug: string;
  name: string;
  menuSlug: string;
  hasConfig: boolean;
  hasDiagnostics: boolean;
  errorOptionSuffix?: string; // defaults to 'last_error'
  settings: Record<string, unknown>;
  defaults: Record<string, unknown>;
  sensitiveKeys: string[];
}

export const PLUGINS: PluginConfig[] = [
  {
    slug: 'headless-clarity',
    name: 'Headless Clarity',
    menuSlug: 'headless-clarity-settings',
    hasConfig: true,
    hasDiagnostics: true,
    settings: {
      project_id: 'abc1234567',
      enable_identify: false,
    },
    defaults: {
      project_id: '',
      enable_identify: true,
    },
    sensitiveKeys: [],
  },
  {
    slug: 'headless-google-analytics',
    name: 'Headless Google Analytics',
    menuSlug: 'headless-google-analytics-settings',
    hasConfig: true,
    hasDiagnostics: true,
    settings: {
      measurement_id: 'G-TEST12345',
      api_secret: 'test_secret_key',
      currency: 'EUR',
      enable_purchase: false,
    },
    defaults: {
      measurement_id: '',
      api_secret: '',
      currency: 'USD',
      enable_purchase: true,
    },
    sensitiveKeys: ['api_secret'],
  },
  {
    slug: 'headless-meta-pixel',
    name: 'Headless Meta Pixel',
    menuSlug: 'headless-meta-pixel-settings',
    hasConfig: true,
    hasDiagnostics: true,
    errorOptionSuffix: 'last_capi_error',
    settings: {
      pixel_id: '123456789012345',
      access_token: 'test_access_token',
      test_event_code: 'TEST12345',
      currency: 'EUR',
      enable_view_content: false,
      enable_add_to_cart: false,
      enable_initiate_checkout: false,
      enable_purchase: false,
      enable_search: false,
      enable_capi: false,
    },
    defaults: {
      pixel_id: '',
      access_token: '',
      test_event_code: '',
      currency: 'USD',
      enable_view_content: true,
      enable_add_to_cart: true,
      enable_initiate_checkout: true,
      enable_purchase: true,
      enable_search: true,
      enable_capi: true,
    },
    sensitiveKeys: ['access_token'],
  },
  {
    slug: 'headless-umami',
    name: 'Headless Umami',
    menuSlug: 'headless-umami-settings',
    hasConfig: true,
    hasDiagnostics: true,
    settings: {
      umami_url: 'https://umami.example.com',
      website_id: '550e8400-e29b-41d4-a716-446655440000',
      enable_purchase: false,
    },
    defaults: {
      umami_url: '',
      website_id: '',
      enable_purchase: true,
    },
    sensitiveKeys: [],
  },
  {
    slug: 'headless-auth',
    name: 'Headless Auth',
    menuSlug: 'headless-auth-settings',
    hasConfig: false,
    hasDiagnostics: false,
    settings: {
      otp_test_mode: true,
      otp_server_url: 'https://otp.example.com/send',
      otp_length: 4,
      otp_expiry: 120,
      max_otp_attempts: 5,
      jwt_access_expiry: 1800,
      jwt_refresh_expiry: 86400,
      max_otp_verify_attempts: 5,
      otp_resend_cooldown: 30,
      rate_limit_window: 600,
      enable_registration: false,
      default_user_role: 'subscriber',
      enable_password_login: true,
      max_login_attempts: 5,
    },
    defaults: {
      otp_test_mode: false,
      otp_server_url: '',
      otp_length: 6,
      otp_expiry: 300,
      max_otp_attempts: 3,
      jwt_access_expiry: 3600,
      jwt_refresh_expiry: 604800,
      max_otp_verify_attempts: 3,
      otp_resend_cooldown: 60,
      rate_limit_window: 900,
      enable_registration: true,
      default_user_role: 'subscriber',
      enable_password_login: true,
      max_login_attempts: 5,
    },
    sensitiveKeys: [],
  },
  {
    slug: 'headless-pos-sessions',
    name: 'Headless POS Sessions',
    menuSlug: 'headless-pos-sessions-settings',
    hasConfig: false,
    hasDiagnostics: false,
    settings: {
      retention_days: 30,
      max_open_sessions: 5,
    },
    defaults: {
      retention_days: 90,
      max_open_sessions: 10,
    },
    sensitiveKeys: [],
  },
  {
    slug: 'headless-fuzzy-find',
    name: 'Headless Fuzzy Find',
    menuSlug: 'headless-fuzzy-find-settings',
    hasConfig: false,
    hasDiagnostics: false,
    settings: {
      weight_title: 8,
      weight_sku: 6,
      weight_content: 4,
      fuzzy_enabled: false,
      autocomplete_enabled: false,
      analytics_enabled: false,
      min_query_length: 3,
      autocomplete_limit: 5,
      did_you_mean_threshold: 5,
      synonyms: 'phone,mobile',
      popular_searches_override: 'tea\ncoffee',
      popular_searches_max: 6,
    },
    defaults: {
      weight_title: 10,
      weight_sku: 8,
      weight_content: 2,
      fuzzy_enabled: true,
      autocomplete_enabled: true,
      analytics_enabled: true,
      min_query_length: 2,
      autocomplete_limit: 8,
      did_you_mean_threshold: 3,
      synonyms: '',
      popular_searches_override: '',
      popular_searches_max: 12,
    },
    sensitiveKeys: [],
  },
  {
    slug: 'headless-storefront',
    name: 'Headless Storefront',
    menuSlug: 'headless-storefront-settings',
    hasConfig: true,
    hasDiagnostics: false,
    settings: {
      app_name: 'E2E Store',
      short_name: 'E2E',
      tagline: 'E2E Test Tagline',
      title_tagline: 'Shop E2E',
      description: 'E2E test store description',
      logo_url: '',
      font_family: 'DM Sans',
      contact: {
        phone: '1800-000-0000',
        phone_href: 'tel:18000000000',
        email: 'test@e2e.com',
        whatsapp_number: '911234567890',
        whatsapp_label: 'WhatsApp E2E',
      },
      social: [{ platform: 'instagram', href: 'https://instagram.com/e2e', label: 'Instagram' }],
      cities: ['Mumbai', 'Delhi'],
      trust_signals: ['Signal A', 'Signal B', 'Signal C', 'Signal D'],
      delivery_message: 'E2E delivery message',
      return_policy: 'E2E return policy',
      delivery_badge: 'Fast',
      hours_text: 'Mon–Sat 9 am – 9 pm',
      delivery_area_text: 'Within 5 km of Bandra West, Mumbai',
      colors: { primary: '#e8622a', secondary: '#d4a017', accent: '#2d9f3f' },
      tokens: {
        section_gap: '3rem',
        card_padding: '1rem',
        card_radius: '1rem',
        button_radius: '9999px',
        image_radius: '0.5rem',
        card_shadow: 'none',
        card_hover_shadow: '0 8px 24px -4px oklch(0 0 0 / 0.12)',
        hover_duration: '300ms',
      },
      frontend_url: '',
      revalidate_secret: '',
      // v1.8 additive fields
      fssai_license: '12345678901234',
      estd_line: 'Since 1987',
      owner_name: 'E2E Owner',
      mov: 200,
      delivery_fee: 25,
      delivery_areas: ['Sector 14', 'Sector 15'],
      template: 'kirana',
      template_config: {
        bakery: { occasions: [], eggless_default: false },
        quickcommerce: { eta_band_minutes: { min: 10, max: 20 }, cod_enabled: true },
        fooddelivery: { veg_only: false, jain_filter_enabled: false },
        ecommerce: { returns_window_days: 7, exchange_enabled: false },
      },
    },
    defaults: {
      app_name: '',
      short_name: '',
      tagline: '',
      title_tagline: '',
      description: '',
      logo_url: '',
      font_family: 'Inter',
      contact: {
        phone: '',
        phone_href: '',
        email: '',
        whatsapp_number: '',
        whatsapp_label: '',
      },
      social: [],
      cities: [],
      trust_signals: ['Genuine Products', 'Easy Returns', 'Secure Payment', 'Fast Delivery'],
      delivery_message: 'Delivery in 1\u20132 business days',
      return_policy:
        'Easy returns within 7 days of delivery. Items must be unused and in original packaging.',
      delivery_badge: '',
      hours_text: '',
      delivery_area_text: '',
      colors: { primary: '#6366f1', secondary: '#64748b', accent: '#94a3b8' },
      tokens: {
        section_gap: '2rem',
        card_padding: '0.75rem',
        card_radius: '0.75rem',
        button_radius: '0.5rem',
        image_radius: '0.5rem',
        card_shadow: 'none',
        card_hover_shadow: '0 4px 12px oklch(0 0 0 / 0.1)',
        hover_duration: '150ms',
      },
      frontend_url: '',
      revalidate_secret: '',
      // v1.8 additive fields. Strings/numbers default to '' (unset);
      // template_config is the fully-shaped admin form skeleton.
      fssai_license: '',
      estd_line: '',
      owner_name: '',
      mov: '',
      delivery_fee: '',
      delivery_areas: [],
      template: '',
      template_config: {
        bakery: { occasions: [], eggless_default: false },
        quickcommerce: { eta_band_minutes: { min: 0, max: 0 }, cod_enabled: false },
        fooddelivery: { veg_only: false, jain_filter_enabled: false },
        ecommerce: { returns_window_days: 0, exchange_enabled: false },
      },
    },
    sensitiveKeys: [],
  },
];
